// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// evalVariogramCpp
arma::vec evalVariogramCpp(const arma::vec& distVec, double psill, double range_, bool modelExp);
RcppExport SEXP _sbivar_evalVariogramCpp(SEXP distVecSEXP, SEXP psillSEXP, SEXP range_SEXP, SEXP modelExpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type distVec(distVecSEXP);
    Rcpp::traits::input_parameter< double >::type psill(psillSEXP);
    Rcpp::traits::input_parameter< double >::type range_(range_SEXP);
    Rcpp::traits::input_parameter< bool >::type modelExp(modelExpSEXP);
    rcpp_result_gen = Rcpp::wrap(evalVariogramCpp(distVec, psill, range_, modelExp));
    return rcpp_result_gen;
END_RCPP
}
// computeSigXws
Rcpp::List computeSigXws(const arma::vec& vgVals, const arma::cube& W);
RcppExport SEXP _sbivar_computeSigXws(SEXP vgValsSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vgVals(vgValsSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(computeSigXws(vgVals, W));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sbivar_evalVariogramCpp", (DL_FUNC) &_sbivar_evalVariogramCpp, 4},
    {"_sbivar_computeSigXws", (DL_FUNC) &_sbivar_computeSigXws, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_sbivar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
