// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// evalVariogramCpp
arma::vec evalVariogramCpp(const arma::vec& distVec, double psill, double range_, bool modelExp);
RcppExport SEXP _sbivar_evalVariogramCpp(SEXP distVecSEXP, SEXP psillSEXP, SEXP range_SEXP, SEXP modelExpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type distVec(distVecSEXP);
    Rcpp::traits::input_parameter< double >::type psill(psillSEXP);
    Rcpp::traits::input_parameter< double >::type range_(range_SEXP);
    Rcpp::traits::input_parameter< bool >::type modelExp(modelExpSEXP);
    rcpp_result_gen = Rcpp::wrap(evalVariogramCpp(distVec, psill, range_, modelExp));
    return rcpp_result_gen;
END_RCPP
}
// computeSigXws
Rcpp::List computeSigXws(const arma::vec& vgVals, const arma::cube& W, bool findSigXws);
RcppExport SEXP _sbivar_computeSigXws(SEXP vgValsSEXP, SEXP WSEXP, SEXP findSigXwsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vgVals(vgValsSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type W(WSEXP);
    Rcpp::traits::input_parameter< bool >::type findSigXws(findSigXwsSEXP);
    rcpp_result_gen = Rcpp::wrap(computeSigXws(vgVals, W, findSigXws));
    return rcpp_result_gen;
END_RCPP
}
// computeTracePPP_cpp
arma::vec computeTracePPP_cpp(const arma::mat& W, const arma::mat& Ey, const arma::mat& vgParY);
RcppExport SEXP _sbivar_computeTracePPP_cpp(SEXP WSEXP, SEXP EySEXP, SEXP vgParYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ey(EySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vgParY(vgParYSEXP);
    rcpp_result_gen = Rcpp::wrap(computeTracePPP_cpp(W, Ey, vgParY));
    return rcpp_result_gen;
END_RCPP
}
// computeIxyAndTracePPP_cpp
Rcpp::List computeIxyAndTracePPP_cpp(const arma::mat& Cx, const arma::mat& Ey, double eta, const arma::mat& Y, const arma::mat& vgParY, double sqrtProdFac, bool findVariances);
RcppExport SEXP _sbivar_computeIxyAndTracePPP_cpp(SEXP CxSEXP, SEXP EySEXP, SEXP etaSEXP, SEXP YSEXP, SEXP vgParYSEXP, SEXP sqrtProdFacSEXP, SEXP findVariancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Cx(CxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ey(EySEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vgParY(vgParYSEXP);
    Rcpp::traits::input_parameter< double >::type sqrtProdFac(sqrtProdFacSEXP);
    Rcpp::traits::input_parameter< bool >::type findVariances(findVariancesSEXP);
    rcpp_result_gen = Rcpp::wrap(computeIxyAndTracePPP_cpp(Cx, Ey, eta, Y, vgParY, sqrtProdFac, findVariances));
    return rcpp_result_gen;
END_RCPP
}
// scoreTestInternals_cpp
Rcpp::List scoreTestInternals_cpp(const arma::mat& P, const arma::cube& crossBlocks, const arma::cube& derivX, const arma::cube& derivY, const arma::vec& vecPos);
RcppExport SEXP _sbivar_scoreTestInternals_cpp(SEXP PSEXP, SEXP crossBlocksSEXP, SEXP derivXSEXP, SEXP derivYSEXP, SEXP vecPosSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type crossBlocks(crossBlocksSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type derivX(derivXSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type derivY(derivYSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vecPos(vecPosSEXP);
    rcpp_result_gen = Rcpp::wrap(scoreTestInternals_cpp(P, crossBlocks, derivX, derivY, vecPos));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sbivar_evalVariogramCpp", (DL_FUNC) &_sbivar_evalVariogramCpp, 4},
    {"_sbivar_computeSigXws", (DL_FUNC) &_sbivar_computeSigXws, 3},
    {"_sbivar_computeTracePPP_cpp", (DL_FUNC) &_sbivar_computeTracePPP_cpp, 3},
    {"_sbivar_computeIxyAndTracePPP_cpp", (DL_FUNC) &_sbivar_computeIxyAndTracePPP_cpp, 7},
    {"_sbivar_scoreTestInternals_cpp", (DL_FUNC) &_sbivar_scoreTestInternals_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_sbivar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
