# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluate Exp or Lin variogram model on a vector of distances
#'
#' Faster C++ replacement for the R \code{evalVariogram} wrapper.
#' Implements the Exponential model (\code{psill * exp(-d / range)}) and
#' the Linear model (\code{psill * (1 - d / range)} for \code{d < range},
#' else 0).
#'
#' @param distVec Numeric vector of pairwise distances
#' @param psill   Partial sill of the structured spatial component
#' @param range_  Range parameter
#' @param modelExp Logical: \code{TRUE} for Exponential, \code{FALSE} for Linear
#' @return Numeric vector of covariance values, same length as \code{distVec}
#' @keywords internal
evalVariogramCpp <- function(distVec, psill, range_, modelExp) {
    .Call(`_sbivar_evalVariogramCpp`, distVec, psill, range_, modelExp)
}

#' Batch-compute lower triangles and traces of \eqn{W_i^T \Sigma_X W_i}
#'
#' For each weight-matrix slice \eqn{W_i} of the \eqn{n \times m \times numWs}
#' array \code{W}, constructs the spatial covariance matrix \eqn{\Sigma_X} from
#' pre-evaluated lower-triangle covariance values and computes
#' \eqn{W_i^T \Sigma_X W_i} (\eqn{m \times m}), returning its lower triangle and
#' trace.
#'
#' The lower-triangle iteration order (column-major) matches R's
#' \code{which(lower.tri(diag(n)))} so that \code{vgVals} can be passed directly
#' from \code{evalVariogramCpp(distX, ...)}, where \code{distX} is
#' \code{as.vector(stats::dist(Cx))}.
#'
#' @param vgVals Covariance values for the strictly lower triangle of
#'   \eqn{\Sigma_X}, in column-major order (length \eqn{n(n-1)/2}).
#'   The diagonal is set to 1 (unit variance after standardisation).
#' @param W \eqn{n \times m \times numWs} array of weight matrices
#' @return A list with
#'   \describe{
#'     \item{sigXws}{\eqn{mm2 \times numWs} matrix, where \eqn{mm2 = m(m-1)/2};
#'       column \eqn{i} holds the lower-triangle entries of \eqn{W_i^T \Sigma_X W_i}
#'       in column-major order.}
#'     \item{traces}{Length-numWs vector of \eqn{tr(W_i^T \Sigma_X W_i)}.}
#'   }
#' @keywords internal
computeSigXws <- function(vgVals, W) {
    .Call(`_sbivar_computeSigXws`, vgVals, W)
}

#' Compute Itautau, Itautheta and score statistics for the GP score test
#'
#' For each length-scale slice \eqn{l}, exploits the block structure of
#' \eqn{\Sigma_{alt,l} = I + \begin{bmatrix}0 & C_l \\ C_l^T & 0\end{bmatrix}}
#' to compute \eqn{P \Sigma_{alt,l}} block-wise without materialising the full
#' \eqn{(n+m)^2 \times L} intermediate array.
#'
#' @param P \eqn{(n+m) \times (n+m)} projection matrix
#' @param crossBlocks \eqn{n \times m \times L} array of cross-blocks \eqn{C_l}
#'   (the off-diagonal blocks of each \eqn{\Sigma_{alt,l}})
#' @param derivX \eqn{n \times n \times 3} covariance-parameter derivative arrays for X
#' @param derivY \eqn{m \times m \times 3} covariance-parameter derivative arrays for Y
#' @param vecPos \eqn{(n+m)} score vector (\eqn{\Omega^{-1}(z - \mu)} for the positive direction)
#' @return A list with
#'   \describe{
#'     \item{Itautau}{Length-\eqn{L} vector of \eqn{0.5\,\|P\Sigma_{alt,l}\|_F^2}}
#'     \item{Itautheta}{\eqn{L \times 6} matrix of trace cross-products with derivative matrices}
#'     \item{UPos}{Length-\eqn{L} vector of score statistics for the positive direction}
#'     \item{UNeg}{Length-\eqn{L} vector of score statistics for the negative direction}
#'   }
#' @keywords internal
scoreTestInternals_cpp <- function(P, crossBlocks, derivX, derivY, vecPos) {
    .Call(`_sbivar_scoreTestInternals_cpp`, P, crossBlocks, derivX, derivY, vecPos)
}

